CREATE TABLE `document_library` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`file_name` varchar(255) NOT NULL,
	`file_url` varchar(500) NOT NULL,
	`file_key` varchar(500) NOT NULL,
	`file_type` varchar(100) NOT NULL,
	`file_size` int NOT NULL,
	`mime_type` varchar(100) NOT NULL,
	`category` varchar(100),
	`tags` text,
	`ai_summary` text,
	`ai_context` text,
	`ai_outcomes` text,
	`ai_processed_at` timestamp,
	`download_count` int NOT NULL DEFAULT 0,
	`is_public` int NOT NULL DEFAULT 1,
	`chat_message_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `document_library_id` PRIMARY KEY(`id`)
);
