CREATE TABLE `shop_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`product_id` int NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`payment_method` enum('points','cash','hybrid') NOT NULL,
	`points_spent` int NOT NULL DEFAULT 0,
	`cash_spent` int NOT NULL DEFAULT 0,
	`status` enum('pending','confirmed','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending',
	`shipping_name` varchar(255),
	`shipping_address` text,
	`shipping_city` varchar(100),
	`shipping_state` varchar(50),
	`shipping_zip` varchar(20),
	`shipping_country` varchar(100),
	`tracking_code` varchar(100),
	`notes` text,
	`admin_notes` text,
	`confirmed_at` timestamp,
	`shipped_at` timestamp,
	`delivered_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shop_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shop_products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`image_url` varchar(500),
	`image_key` varchar(500),
	`category` enum('physical','digital','experience','badge') NOT NULL DEFAULT 'physical',
	`points_price` int NOT NULL DEFAULT 0,
	`cash_price` int NOT NULL DEFAULT 0,
	`stock` int NOT NULL DEFAULT -1,
	`min_level` int NOT NULL DEFAULT 1,
	`is_limited` int NOT NULL DEFAULT 0,
	`is_active` int NOT NULL DEFAULT 1,
	`total_sold` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shop_products_id` PRIMARY KEY(`id`)
);
